apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ahmedbenrejeb0/backend:a90d0b2ffb7761467358c2b24e11e8299dfedb44
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: game-config
            - secretRef:
                name: game-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30  # Wait 30s for NestJS to boot before asking "Are you alive?"
            periodSeconds: 10        # Check every 10s
            failureThreshold: 5     # If it fails 5 times (50s), kill it.

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10  # Wait 10s before checking "Can you take traffic?"
            periodSeconds: 10           # Check every 5s
            successThreshold: 1      # If it says "OK" once, open the gates!
            failureThreshold: 5      # If it fails 3 times, close the gates.
            timeoutSeconds: 5

              
          
